---
cro: 1
id: CSSTidy
env:  []
endpoints: 
  - 
    host-env: CSSTIDY_HOST
    protocol: https
    id: https
    port-env: CSSTIDY_PORT
    name: HTTPS
entrypoint: service.raku
links:  []
name: CSSTidy
...